spring:
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/tehnosky
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true